In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [8]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [9]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [11]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [13]:
list(np.linspace(1,5,20, retstep=True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [14]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,4,2)) * 6

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [23]:
np.empty((2,3))

array([[4.66099171e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
a=np.eye(4)

In [26]:
a.shape

(4, 4)

In [27]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
a.size

16

In [29]:
a.ndim

2

In [30]:
a1=np.random.randn(3,4)

In [31]:
a1

array([[ 0.35624175,  0.20998237, -0.59742698, -1.13762626],
       [ 1.46984935, -0.86299468, -1.20490489,  0.88080818],
       [-0.7977952 ,  0.3691516 , -0.02947558, -0.26822382]])

In [32]:
import pandas as pd

In [33]:
pd.DataFrame(a1)

0         1         2         3
0  0.356242  0.209982 -0.597427 -1.137626
1  1.469849 -0.862995 -1.204905  0.880808
2 -0.797795  0.369152 -0.029476 -0.268224

In [34]:
a1

array([[ 0.35624175,  0.20998237, -0.59742698, -1.13762626],
       [ 1.46984935, -0.86299468, -1.20490489,  0.88080818],
       [-0.7977952 ,  0.3691516 , -0.02947558, -0.26822382]])

In [35]:
a1[1][1]

-0.8629946812540896

In [36]:
a1[0:2,0:2]

array([[ 0.35624175,  0.20998237],
       [ 1.46984935, -0.86299468]])

In [37]:
a1[[0,1],0:2]

array([[ 0.35624175,  0.20998237],
       [ 1.46984935, -0.86299468]])

In [38]:
a1

array([[ 0.35624175,  0.20998237, -0.59742698, -1.13762626],
       [ 1.46984935, -0.86299468, -1.20490489,  0.88080818],
       [-0.7977952 ,  0.3691516 , -0.02947558, -0.26822382]])

In [39]:
a1[[1,2],3]

array([ 0.88080818, -0.26822382])

In [40]:
np.random.randint(1,3,(3,3))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [42]:
m1=np.random.randint(1,3,(3,3))

In [43]:
m1

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [44]:
m2=np.random.randint(2,4,(3,3))

In [45]:
m2

array([[3, 2, 3],
       [3, 2, 3],
       [3, 3, 3]])

In [46]:
m1*m2

array([[3, 2, 3],
       [3, 4, 6],
       [3, 6, 6]])

In [47]:
m1@m2

array([[ 9,  7,  9],
       [15, 12, 15],
       [15, 12, 15]])

In [48]:
m1

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [49]:
pow(m1,2)

array([[1, 1, 1],
       [1, 4, 4],
       [1, 4, 4]])

In [50]:
np.sqrt(m1)

array([[1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [53]:
np.log10(m1)

array([[0.     , 0.     , 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103]])

In [54]:
np.exp(m1)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [55]:
m1**2

array([[1, 1, 1],
       [1, 4, 4],
       [1, 4, 4]])